### ISSUE TITLE
Frame Per Second (FPS) issue

### ISSUE THREAD

**Issue by erictsai1224tw** [facebookresearch/sam2#357]
Hi, 

Thanks for providing this awesome research work, which let me can conduct my research based on your contribution.
I found an issue about FPS, and I am not sure if there is any setting that I missed. 
The inferenced in SAM2 was on RTX4090 GPU with "sam2.1_hiera_small.pt" pretrain weight and its model. However, I only got 9.23 FPS.
I got this number from measured the function
`masks, scores, _ = predictor.predict()`, predictor is function `SAM2ImagePredictor`
I traced the code to the file: sam2/sam2_image_predictor.py, class SAM2ImagePredictor -> func _predict -> `low_res_masks, iou_predictions, _, _ = self.model.sam_mask_decoder`,
I found the bottleneck resulted low FPS seems from here. I want to ask is this normal, or there is any setting I missed. And the most important I want to know is, is there any way to boost the FPS?

Thanks again for your great research!

**Comment by erictsai1224tw** [comment]
I find the bottleneck seems at `sam2/modeling/sam/mask_decoder.py`
`MaskDecoder `-> `predict_masks`->`upscaled_embedding = act1(ln1(dc1(src) + feat_s1))` and 'upscaled_embedding = act2(dc2(upscaled_embedding) + feat_s0)'
each of them cost 0.04s to computing, so they sum up to be 0.08s, which means only 12.5 FPS
Is there any suggestion? Thanks!

**Comment by heyoeyo** [comment]
The numbers you're getting are roughly the speed expected from using CPU-only, so it'd be worth checking if the GPU is actually being used (try printing out: `predictor.device`).
For the `predict` step on it's own, a 4090 should manage well over 500fps, and even with the (slower) image encoding step (`set_image`) it should probably still be over 60fps for the small model.

**Comment by erictsai1224tw** [comment]
Hi @heyoeyo ,

Thanks for your reply! I have checked the data that put into the model, those data were on the cuda I confimed. Also, the `predictor.device` is shown cuda too. Did you think is there any other issue that may happened? Thanks again for your suggestion!

**Comment by heyoeyo** [comment]
That seems very strange! Is it possible that the GPU is busy doing other work in the background? Or are there multiple GPUs in the system (and maybe a slower one is being used instead of the 4090)?

One thing worth checking is running using the CPU to see how fast that runs. If it's the same speed, that's a good hint that somehow the GPU isn't being used for some reason. If it turns out to be _faster_ then that may be a hint that there's something going wrong using the GPU (maybe the drivers would need to be updated).
Another thing to check is what happens when running the larger models. The `predict` step should actually run the same speed for all model sizes, so if the timing changes with different model sizes, there might something else going on (or maybe the timing is including other steps for example).

**Comment by erictsai1224tw** [comment]
Our server comes with 1*4090 and 6*3090. I sure it's on 4090, is observed from nvidia-smi list during inference, cost 1G VRAM and did not do other thing in the mean time. I also tried with the different model size, and the speed are almost same as you mentioned.
I have evaluated on cpu only just now, and i found its speed is same as the previous one i measured. That is a great debugging entry point, pretty thanks for your advice! I will update once more information comes in!

**Comment by erictsai1224tw** [comment]
Hi I find the reason! I measured in first predict frame, it may do some initialization steps such as memory bank in the first step, so the speed was reduced lots. And if I measured in the next coming frames, the FPS was reached to >100 FPS although sometimes it reduces to 50 fps. 
![image](https://github.com/user-attachments/assets/0ec3b557-5c47-4c01-a170-9d0f1db146a3)
Really appreciate for your suggestion and help!
